name: Deploy master
on:
  push:
    branches:
      - master

jobs:
  deploy_prod:
    uses: ./.github/workflows/partial-deploy.yml
    permissions:
      contents: write
      issues: write
      packages: read
    with:
      environment: prod
      githubRelease: true
    secrets:
      aad_credentials: ${{ secrets.AZUREAD_CREDENTIALS_PROD }}
      terraform_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      pagerduty_api_token: ${{ secrets.PAGERDUTY_API_TOKEN_PROD }}
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}