name: CI - Pull Request
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TF_WORKSPACE: prod
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pre-requisites
        run: |
          yarn
          sudo wget -O /usr/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          sudo chmod a+x /usr/bin/sops

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: Terraform Init
        run: yarn run init

      - name: Verify Terraform formatting
        run: yarn run format:check

      - name: Validate Terraform
        run: yarn run validate
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}

      - name: Dump secrets
        run: |
            echo $SOPS_AGE_KEY &gt; /tmp/.env
            echo $TF_VAR_aad_credentials &gt;&gt; /tmp/.env
            echo $TF_VAR_cloudflare_api_token &gt;&gt; /tmp/.env
            echo $TF_VAR_pagerduty_api_token &gt;&gt; /tmp/.env
        shell: bash
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}
          TF_VAR_aad_credentials: ${{ secrets.AZUREAD_CREDENTIALS_PROD }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_pagerduty_api_token: '${{ secrets.PAGERDUTY_API_TOKEN_PROD }}'

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
          limit-access-to-users: lholota

      - name: Apply terraform
        run: |
          yarn run apply
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}
          TF_VAR_aad_credentials: ${{ secrets.AZUREAD_CREDENTIALS_PROD }}
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_pagerduty_api_token: '${{ secrets.PAGERDUTY_API_TOKEN_PROD }}'
