name: Terraform apply

on:
  workflow_call:
    inputs:
      githubRelease:
        type: boolean
        required: true
      environment:
        required: true
        type: string
    secrets:
      aad_credentials:
        required: true
      terraform_token:
        required: true
      cloudflare_api_token:
        required: true
      pagerduty_api_token:
        required: true
      sops_age_key:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to allow adding git tags
      issues: write # to allow linking issues to releases
      packages: read
    env:
      TF_WORKSPACE: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Install pre-requisites
        run: |
          yarn
          sudo wget -O /usr/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          sudo chmod a+x /usr/bin/sops

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.terraform_token }}

      - name: Terraform Init
        id: init
        run: yarn run init

      - name: Verify Terraform formatting
        id: fmt
        run: yarn run format:check

      - name: Validate Terraform
        id: validate
        run: yarn run validate
        env:
          SOPS_AGE_KEY: ${{ secrets.sops_age_key }}

      - name: "Determine release version and create git tag"
        uses: docker://ghcr.io/codfish/semantic-release-action:v1.9.0
        if: ${{ inputs.githubRelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply terraform
        run: yarn run ${{ inputs.environment }}:apply
        env:
          SOPS_AGE_KEY: ${{ secrets.sops_age_key }}
          TF_VAR_aad_credentials: ${{ secrets.aad_credentials }}
          TF_VAR_cloudflare_api_token: ${{ secrets.cloudflare_api_token }}
          TF_VAR_pagerduty_api_token: '${{ secrets.pagerduty_api_token }}'